//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SchoolManager.Domain.Entities
{
    [DataContract(IsReference = true)]
    public partial class ASPStateTempSessions
    {
        [DataMember]
        public string SessionId { get; set; }
        [DataMember]
        public System.DateTime Created { get; set; }
        [DataMember]
        public System.DateTime Expires { get; set; }
        [DataMember]
        public System.DateTime LockDate { get; set; }
        [DataMember]
        public System.DateTime LockDateLocal { get; set; }
        [DataMember]
        public int LockCookie { get; set; }
        [DataMember]
        public int Timeout { get; set; }
        [DataMember]
        public bool Locked { get; set; }
        [DataMember]
        public byte[] SessionItemShort { get; set; }
        [DataMember]
        public byte[] SessionItemLong { get; set; }
        [DataMember]
        public int Flags { get; set; }
    }
    
}
