//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SchoolManager.Domain.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(User))]
    public partial class Book
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Title { get; set; }
        [DataMember]
        public string Link { get; set; }
        [DataMember]
        public string Description { get; set; }
        [DataMember]
        public string Author { get; set; }
        [DataMember]
        public Nullable<bool> Highlighted { get; set; }
        [DataMember]
        public string Year { get; set; }
        [DataMember]
        public string Origin { get; set; }
        [DataMember]
        public string Editorial { get; set; }
    
        [DataMember]
        public virtual User User { get; set; }
    }
    
}
