//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SchoolManager.Domain.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(User))]
    [KnownType(typeof(Classroom))]
    public partial class Event
    {
        [DataMember]
        public long Id { get; set; }
        [DataMember]
        public System.DateTime start { get; set; }
        [DataMember]
        public System.DateTime end { get; set; }
        [DataMember]
        public string title { get; set; }
        [DataMember]
        public string description { get; set; }
        [DataMember]
        public string url { get; set; }
        [DataMember]
        public string backgroundColor { get; set; }
        [DataMember]
        public string borderColor { get; set; }
        [DataMember]
        public string textColor { get; set; }
        [DataMember]
        public string extendedProps { get; set; }
        [DataMember]
        public int userId { get; set; }
        [DataMember]
        public Nullable<int> classroomId { get; set; }
        [DataMember]
        public string students { get; set; }
    
        [DataMember]
        public virtual User User { get; set; }
        [DataMember]
        public virtual Classroom Classroom { get; set; }
    }
    
}
