//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SchoolManager.Domain.Entities
{
    [DataContract(IsReference = true)]
    public partial class Gallery
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Title { get; set; }
        [DataMember]
        public string Description { get; set; }
        [DataMember]
        public Nullable<System.DateTime> CreationDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> UpdateDate { get; set; }
        [DataMember]
        public string FlickrAlbum { get; set; }
    }
    
}
