//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SchoolManager.Domain.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(User))]
    [KnownType(typeof(Reply))]
    [KnownType(typeof(Classroom))]
    public partial class Post
    {
        public Post()
        {
            this.Public = false;
            this.Replies = new HashSet<Reply>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Title { get; set; }
        [DataMember]
        public string Text { get; set; }
        [DataMember]
        public System.DateTime Date { get; set; }
        [DataMember]
        public int Category { get; set; }
        [DataMember]
        public int UserId { get; set; }
        [DataMember]
        public string FlickrAlbum { get; set; }
        [DataMember]
        public bool Public { get; set; }
        [DataMember]
        public Nullable<int> Subject { get; set; }
        [DataMember]
        public string YouTubeVideo { get; set; }
    
        [DataMember]
        public virtual User User { get; set; }
        [DataMember]
        public virtual ICollection<Reply> Replies { get; set; }
        [DataMember]
        public virtual Classroom Classroom { get; set; }
    }
    
}
