//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SchoolManager.Domain.Entities
{
    [DataContract(IsReference = true)]
    public partial class RegistrationRequest
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Level { get; set; }
        [DataMember]
        public string Year { get; set; }
        [DataMember]
        public string Turn { get; set; }
        [DataMember]
        public string Lastnames { get; set; }
        [DataMember]
        public string Firstnames { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Birthday { get; set; }
        [DataMember]
        public string Birthplace { get; set; }
        [DataMember]
        public string DNI { get; set; }
        [DataMember]
        public string Sex { get; set; }
        [DataMember]
        public string AdressStreet { get; set; }
        [DataMember]
        public Nullable<int> AdressNumber { get; set; }
        [DataMember]
        public string AdressFloor { get; set; }
        [DataMember]
        public string AdressDpto { get; set; }
        [DataMember]
        public string Localidad { get; set; }
        [DataMember]
        public Nullable<int> PostalCode { get; set; }
        [DataMember]
        public string FamilyPhone { get; set; }
        [DataMember]
        public string CellPhone { get; set; }
        [DataMember]
        public string OtherPhones { get; set; }
        [DataMember]
        public string EmailFather { get; set; }
        [DataMember]
        public string EmailMother { get; set; }
        [DataMember]
        public Nullable<byte> HMB { get; set; }
        [DataMember]
        public Nullable<byte> HMITS { get; set; }
        [DataMember]
        public string BDB { get; set; }
        [DataMember]
        public string Language { get; set; }
        [DataMember]
        public Nullable<bool> OtherSchool { get; set; }
        [DataMember]
        public string Distrito { get; set; }
        [DataMember]
        public string OtherSchoolLevel { get; set; }
        [DataMember]
        public string NameSchool { get; set; }
        [DataMember]
        public Nullable<long> NumberSchool { get; set; }
        [DataMember]
        public Nullable<bool> Private { get; set; }
        [DataMember]
        public string SocialName { get; set; }
        [DataMember]
        public string AffiliateSocialNumber { get; set; }
        [DataMember]
        public string MothersName { get; set; }
        [DataMember]
        public string MothersProfession { get; set; }
        [DataMember]
        public string MothersNationality { get; set; }
        [DataMember]
        public string MothersLevelInstruction { get; set; }
        [DataMember]
        public Nullable<bool> MothersLevelInstructionCompleted { get; set; }
        [DataMember]
        public string MothersUntilYearLevel { get; set; }
        [DataMember]
        public Nullable<bool> MothersLive { get; set; }
        [DataMember]
        public string MothersKindOfDocument { get; set; }
        [DataMember]
        public Nullable<long> MothersDocumentNumber { get; set; }
        [DataMember]
        public string MothersAddressStreet { get; set; }
        [DataMember]
        public string MothersAddressNumber { get; set; }
        [DataMember]
        public string MothersAddressFloor { get; set; }
        [DataMember]
        public string MothersAddressTower { get; set; }
        [DataMember]
        public string MothersAddressDpto { get; set; }
        [DataMember]
        public string MothersLocalidad { get; set; }
        [DataMember]
        public Nullable<long> MothersPostalCode { get; set; }
        [DataMember]
        public string MothersPhone { get; set; }
        [DataMember]
        public string MothersWorkPhone { get; set; }
        [DataMember]
        public string FathersName { get; set; }
        [DataMember]
        public string FathersProfession { get; set; }
        [DataMember]
        public string FathersNationality { get; set; }
        [DataMember]
        public string FathersLevelInstruction { get; set; }
        [DataMember]
        public Nullable<bool> FathersLevelInstructionCompleted { get; set; }
        [DataMember]
        public string FathersUntilYearLevel { get; set; }
        [DataMember]
        public Nullable<bool> FathersLive { get; set; }
        [DataMember]
        public string FathersKindofDocument { get; set; }
        [DataMember]
        public Nullable<long> FathersDocumentNumber { get; set; }
        [DataMember]
        public string FathersAddressStreet { get; set; }
        [DataMember]
        public string FathersAddressNumber { get; set; }
        [DataMember]
        public string FathersAddressFloor { get; set; }
        [DataMember]
        public string FathersAddressTower { get; set; }
        [DataMember]
        public string FathersAddressDpto { get; set; }
        [DataMember]
        public string FathersLocalidad { get; set; }
        [DataMember]
        public Nullable<long> FathersPostalCode { get; set; }
        [DataMember]
        public string FathersPhone { get; set; }
        [DataMember]
        public string FathersWorkPhone { get; set; }
        [DataMember]
        public string TutorName { get; set; }
        [DataMember]
        public string TutorProfession { get; set; }
        [DataMember]
        public string TutorNationality { get; set; }
        [DataMember]
        public string TutorLevelInstruction { get; set; }
        [DataMember]
        public Nullable<bool> TutorLevelInstructionCompleted { get; set; }
        [DataMember]
        public string TutorUntilYearLevel { get; set; }
        [DataMember]
        public Nullable<bool> TutorLive { get; set; }
        [DataMember]
        public string TutorKindOfDocument { get; set; }
        [DataMember]
        public Nullable<long> TutorDocumentNumber { get; set; }
        [DataMember]
        public string TutorAddressStreet { get; set; }
        [DataMember]
        public string TutorAddressNumber { get; set; }
        [DataMember]
        public string TutorAddressFloor { get; set; }
        [DataMember]
        public string TutorAddressTower { get; set; }
        [DataMember]
        public string TutorAddressDpto { get; set; }
        [DataMember]
        public string TutorLocalidad { get; set; }
        [DataMember]
        public Nullable<long> TutorPostalCode { get; set; }
        [DataMember]
        public string TutorPhone { get; set; }
        [DataMember]
        public string TutorWorkPhone { get; set; }
        [DataMember]
        public string OtherPersonsName { get; set; }
        [DataMember]
        public string PersonKindDocument { get; set; }
        [DataMember]
        public Nullable<long> PersonDocumentNumber { get; set; }
        [DataMember]
        public int YearRequest { get; set; }
        [DataMember]
        public string Status { get; set; }
        [DataMember]
        public Nullable<bool> HealthCompleted { get; set; }
        [DataMember]
        public Nullable<bool> HealthUpdated { get; set; }
        [DataMember]
        public string OtherLevel { get; set; }
    }
    
}
