//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SchoolManager.Domain.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Post))]
    [KnownType(typeof(User))]
    public partial class Reply
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Text { get; set; }
        [DataMember]
        public System.DateTime Date { get; set; }
        [DataMember]
        public int PostId { get; set; }
        [DataMember]
        public int UserId { get; set; }
    
        [DataMember]
        public virtual Post Post { get; set; }
        [DataMember]
        public virtual User User { get; set; }
    }
    
}
